### ISSUE TITLE
vmprof hangs

### ISSUE THREAD

**Issue by planrich** [vmprof/vmprof-python#122]
A single threaded application hangs in the following stack trace:

```
#0  0x00007ffff7bc9827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0,
    futex_word=0x7fffe4002d90) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x7fffe4002d90, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007ffff7bc98d4 in __new_sem_wait_slow (sem=0x7fffe4002d90, abstime=0x0) at sem_waitcommon.c:181
#3  0x00007ffff7bc997a in __new_sem_wait (sem=<optimised out>) at sem_wait.c:29
#4  0x000000000049f634 in PyThread_acquire_lock ()
#5  0x00000000005640e2 in ?? ()
#6  0x00000000004c41da in PyEval_EvalFrameEx ()
#7  0x00007ffff6800baa in vmprof_eval (f=<optimised out>, throwflag=<optimised out>) at src/_vmprof.c:55
#8  0x00000000004c22e5 in PyEval_EvalCodeEx ()
#9  0x00000000004c9c59 in PyEval_EvalFrameEx ()
#10 0x00007ffff6800baa in vmprof_eval (f=<optimised out>, throwflag=<optimised out>) at src/_vmprof.c:55
#11 0x00000000004c22e5 in PyEval_EvalCodeEx ()
#12 0x00000000004c9c59 in PyEval_EvalFrameEx ()
#13 0x00007ffff6800baa in vmprof_eval (f=<optimised out>, throwflag=<optimised out>) at src/_vmprof.c:55
#14 0x00000000004c22e5 in PyEval_EvalCodeEx ()
#15 0x00000000004de7fe in ?? ()
#16 0x00000000004b0de3 in PyObject_Call ()
#17 0x00000000004f49ae in ?? ()
#18 0x00000000004b0de3 in PyObject_Call ()
#19 0x00000000004ce140 in PyEval_CallObjectWithKeywords ()
#20 0x0000000000597822 in ?? ()
#21 0x00007ffff7bc16ba in start_thread (arg=0x7fffe9963700) at pthread_create.c:333
#22 0x00007ffff78f782d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

It is very strange that no signal is involved.

**Comment by planrich** [comment]
Need more info to reproduce.
