### ISSUE TITLE
Error reading vmprof file

### ISSUE THREAD

**Issue by claeyswo** [vmprof/vmprof-python#125]
When trying to profile WSGI app, same as https://github.com/vmprof/vmprof-python/issues/28.

These are the resulting files:

https://www.dropbox.com/s/45wn4ipwne52jgf/vmprof.out-26922?dl=0
https://www.dropbox.com/s/br6o13giq4uhpnw/vmprof.out-26925?dl=0

When trying to read them I get the following error:

```>>> vmprof.read_profile('vmprof.out-26925')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/projects/geoportaal/venv/local/lib/python2.7/site-packages/vmprof/profiler.py", line 37, in read_profile
    period, profiles, virtual_symbols, interp_name, meta, start_time, end_time = read_prof(prof_file)
  File "/var/projects/geoportaal/venv/local/lib/python2.7/site-packages/vmprof/reader.py", line 323, in read_prof
    reader.read_all()
  File "/var/projects/geoportaal/venv/local/lib/python2.7/site-packages/vmprof/reader.py", line 256, in read_all
    self.read_static_header()
  File "/var/projects/geoportaal/venv/local/lib/python2.7/site-packages/vmprof/reader.py", line 143, in read_static_header
    assert self.read_word() == 0 # header count
AssertionError```

**Comment by planrich** [comment]
I have just now pushed a solution to this problem d4c10d351. Short explanation:

when the callback registered to atexit is invoked disable will call back to python land and write some more information to the log. This did not succeed in the case of atexit.

I fixed that by using the code that is used by pypy to write back that information in C and avoid the callback to Python.

This should not have affected the usual invocation:

`$ python -m vmprof script.py`

**Comment by claeyswo** [comment]
Great, thanks! I suspected something like that. Any idea when the next release will be?

**Comment by claeyswo** [comment]
Just for the record, I am indeed hitting [this exception](https://github.com/vmprof/vmprof-python/blob/master/vmprof/__init__.py#L36) when calling disable.

```
   File "/var/projects/geoportaal/venv/local/lib/python2.7/site-packages/vmprof/__init__.py", line 36, in disable
     raise Exception("Error while writing profile: " + str(e))
 Exception: Error while writing profile: [Errno 9] Bad file descriptor
```

**Comment by planrich** [comment]
Today, I'm preparing 0.4.3 just now.

**Comment by claeyswo** [comment]
Can confirm that it is fixed. Thanks a lot!
