### ISSUE TITLE
vmprof.disable() fails on CPython 3.4

### ISSUE THREAD

**Issue by methane** [vmprof/vmprof-python#13]
```
Traceback (most recent call last):
  File "./main.py", line 39, in <module>
    vmprof.disable()
  File "/home/vagrant/vmprof-python/vmprof/__init__.py", line 53, in disable
    _virtual_ips_so_far = read_prof(f, virtual_ips_only=True)
  File "/home/vagrant/vmprof-python/vmprof/reader.py", line 101, in read_prof
    assert read_word(fileobj) == 0 # header count
  File "/home/vagrant/vmprof-python/vmprof/reader.py", line 87, in read_word
    b = fileobj.read(8)
OSError: [Errno 9] Bad file descriptor
```

**Comment by methane** [comment]
I've passed fd opened with `open(path, 'wb')`, while filemode should be 'w+b'.
