### ISSUE TITLE
Broken pipe when uploading a 209 MB profile 

### ISSUE THREAD

**Issue by brechtm** [vmprof/vmprof-python#132]
```
$ ll pypy.vmprof
-rw-r--r--  1 brechtm  staff   209M Apr 13 13:32 pypy.vmprof
$ /tmp/pypy/pypy3-v5.7.1-src/pypy3-c -m vmprof.upload --web-auth 9529e2abb60a3bce73a20f50dc77e42b24fb50c9 pypy.vmprof
Uploading to http://vmprof.com...
 => Uploading the cpu profile...
Traceback (most recent call last):
  File "/tmp/pypy/pypy3-v5.7.1-src/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/tmp/pypy/pypy3-v5.7.1-src/site-packages/requests/packages/urllib3/connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/tmp/pypy/pypy3-v5.7.1-src/lib-python/3/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/tmp/pypy/pypy3-v5.7.1-src/lib-python/3/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/tmp/pypy/pypy3-v5.7.1-src/lib-python/3/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/tmp/pypy/pypy3-v5.7.1-src/lib-python/3/http/client.py", line 936, in _send_output
    self.send(message_body)
  File "/tmp/pypy/pypy3-v5.7.1-src/lib-python/3/http/client.py", line 908, in send
    self.sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/pypy/pypy3-v5.7.1-src/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/tmp/pypy/pypy3-v5.7.1-src/site-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/tmp/pypy/pypy3-v5.7.1-src/site-packages/requests/packages/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/tmp/pypy/pypy3-v5.7.1-src/site-packages/requests/packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/tmp/pypy/pypy3-v5.7.1-src/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/tmp/pypy/pypy3-v5.7.1-src/site-packages/requests/packages/urllib3/connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/tmp/pypy/pypy3-v5.7.1-src/lib-python/3/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/tmp/pypy/pypy3-v5.7.1-src/lib-python/3/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/tmp/pypy/pypy3-v5.7.1-src/lib-python/3/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/tmp/pypy/pypy3-v5.7.1-src/lib-python/3/http/client.py", line 936, in _send_output
    self.send(message_body)
  File "/tmp/pypy/pypy3-v5.7.1-src/lib-python/3/http/client.py", line 908, in send
    self.sock.sendall(data)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/pypy/pypy3-v5.7.1-src/lib-python/3/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/tmp/pypy/pypy3-v5.7.1-src/lib-python/3/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/pypy/pypy3-v5.7.1-src/site-packages/vmprof/upload.py", line 22, in <module>
    main()
  File "/tmp/pypy/pypy3-v5.7.1-src/site-packages/vmprof/upload.py", line 19, in main
    'VM': interpname })
  File "/tmp/pypy/pypy3-v5.7.1-src/site-packages/vmshare/service.py", line 113, in post
    Service.FILE_CPU_PROFILE, compress=False)
  File "/tmp/pypy/pypy3-v5.7.1-src/site-packages/vmshare/service.py", line 94, in post_file
    response = requests.post(url, headers=headers, files=files)
  File "/tmp/pypy/pypy3-v5.7.1-src/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/tmp/pypy/pypy3-v5.7.1-src/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/tmp/pypy/pypy3-v5.7.1-src/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/tmp/pypy/pypy3-v5.7.1-src/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/tmp/pypy/pypy3-v5.7.1-src/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
```

A second attempt suffered the same problem.

Uploading a 9.4 MB profile was succesful.

**Comment by planrich** [comment]
As far as I remember the limit for profiles is around 70 MB. nginx will cut of profiles that are longer... If you need more, I would suggest to install the server locally. You can find the repo here: https://github.com/vmprof/vmprof-server

Maybe we could think about increasing the limit.

**Comment by brechtm** [comment]
It would be good to display an error message to inform the user about what the problem is.

**Comment by fijal** [comment]
Hi Brecht

We thought a lot about making the online-collection a thing (that is the profile gets uploaded constantly and the information displayed in real time). At the end of the day the idea got cut because of lack of potential funding. If you think someone would be interested in paying for this feature commercially, I'm happy to reconsider

**Comment by brechtm** [comment]
I understand. The troubles of open source...

Would it be possible to query the server for the maximum upload size somehow? Or can the limit (70 MB? A 118 MB profile also failed to upload) be hard-coded into vmprof and checked when uploading to vmprof.com?

**Comment by planrich** [comment]
Yes, that is even better than my solution in the last commit. I'll have to lookup the exact amount on the server (wrong pc now)

**Comment by brechtm** [comment]
So vmprof-server requires a PostgreSQL server? Or can it also run on SQLite? If not, I might look into writing a Dockerfile for a vmprof server. Not promises as to when I'll get to that though...

**Comment by planrich** [comment]
Good. I have now added a warning when the file exceeds 100 MB. I have also increased the max request size to 100MB (+ ~2MB for the html header). The total amount of data uploaded is sizable.

**Comment by planrich** [comment]
I'm closing this issue for now!
