### ISSUE TITLE
"AssertionError: not a marker" when using certain modules

### ISSUE THREAD

**Issue by bluenote10** [vmprof/vmprof-python#136]
This might be a duplicate of #135, but I'm getting a different traceback.

Running `python -m vmprof <test-file>.py` gives the following error:

```
unknown marker 0x0
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/tmpvenv/lib/python2.7/site-packages/vmprof/__main__.py", line 75, in <module>
    main()
  File "/tmp/tmpvenv/lib/python2.7/site-packages/vmprof/__main__.py", line 71, in main
    show_stats(prof_name, output_mode, args)
  File "/tmp/tmpvenv/lib/python2.7/site-packages/vmprof/__main__.py", line 20, in show_stats
    stats = vmprof.read_profile(filename)
  File "/tmp/tmpvenv/local/lib/python2.7/site-packages/vmprof/profiler.py", line 38, in read_profile
    state = _read_prof(prof_file)
  File "/tmp/tmpvenv/local/lib/python2.7/site-packages/vmprof/reader.py", line 323, in _read_prof
    reader.read_all()
  File "/tmp/tmpvenv/local/lib/python2.7/site-packages/vmprof/reader.py", line 296, in read_all
    assert not marker, (fileobj.tell(), repr(marker))
AssertionError: (47878, "'\\x00'")
```

The error seems to be triggered by using certain modules. If the file is plain Python code, everything works fine. The following two examples crash though (at the end of the execution):

```python
# test_ipython.py
import IPython
IPython.embed()
```

```python
# test_tensorflow.py
from __future__ import print_function
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))
```

VMProf version: 0.4.4
Python version: 2.7.3
System: Ubuntu 12.04
Virtual env: Fresh venv, basically with pip install `vmprof`, `tensorflow`, `ipython<6`

Downgrading from vmprof 0.4.4 to 0.4.3 seems to solve the issue.

**Comment by planrich** [comment]
Can you try to do `pip install --pre vmprof` to install 0.4.5.dev0 and try again?

**Comment by bluenote10** [comment]
Yes, that seems to work, thanks!
