### ISSUE TITLE
vmprof disable appears broken on PyPy 5.7.1

### ISSUE THREAD

**Issue by rowillia** [vmprof/vmprof-python#141]
```
Python 2.7.13 (5.7.1+dfsg-2ubuntu1~ppa1~ubuntu14.04, May 02 2017, 19:33:41)
[PyPy 5.7.1 with GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> import vmprof
>>>> import tempfile
>>>> fileno, path = tempfile.mkstemp(prefix="vmprof", suffix=".output")
>>>> vmprof.enable(fileno)
>>>> vmprof.disable()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/service_venv_pypy/site-packages/vmprof/__init__.py", line 33, in disable
    _vmprof.disable(only_needed)
TypeError: disable() takes no arguments (1 given)
```

**Comment by planrich** [comment]
Sorry for that, one of the pull requests changed the API and I overlooked that! Can you try to install the pre release version (0.4.6.dev1?)

**Comment by soonum** [comment]
Hi there, 
I was facing the same issue, now everything is good with the 0.4.6.dev1 version. 
Thanks.

**Comment by nealmcb** [comment]
Thanks for the workaround for the problem with `vmprof-0.4.5`. To be more specific, it worked to

 `pip install --user vmprof==0.4.6.dev1`

Was this the fix?  https://github.com/vmprof/vmprof-python/tree/fix-pypy-5.8
Anything else you need before releasing this to pypi?
