### ISSUE TITLE
AssertionError in vmprofshow gives not very helpful error

### ISSUE THREAD

**Issue by boxed** [vmprof/vmprof-python#154]
First try of using vmprof.. I've generated a 14 meg profiler with --line and --mem flags on, tried to run vmprofshow and get:

```
Fatal: could not read vmprof profile file 'vmprof_unit_tests.prof': 
```

Searched the code for that error and found it here: https://github.com/vmprof/vmprof-python/blob/ca0c4e013acd885773b307d43d2ed8570ec16eb9/vmprof/show.py#L36

That way of formatting exception output isn't very good as you can see as the type is lost and sometimes the type is all the data there was (plus the stack trace, which is also lost). After changing the line below from return to raise I get:

```
Traceback (most recent call last):
  File "/Users/andersh/triresolve/env/bin/vmprofshow", line 11, in <module>
    sys.exit(main())
  File "/Users/andersh/triresolve/env/lib/python2.7/site-packages/vmprof/show.py", line 263, in main
    pp.show(args.profile)
  File "/Users/andersh/triresolve/env/lib/python2.7/site-packages/vmprof/show.py", line 35, in show
    stats = vmprof.read_profile(profile)
  File "/Users/andersh/triresolve/env/lib/python2.7/site-packages/vmprof/profiler.py", line 49, in read_profile
    meta=state.meta, state=state)
  File "/Users/andersh/triresolve/env/lib/python2.7/site-packages/vmprof/stats.py", line 21, in __init__
    self.generate_top()
  File "/Users/andersh/triresolve/env/lib/python2.7/site-packages/vmprof/stats.py", line 73, in generate_top
    assert addr <= 0
AssertionError
```

**Comment by boxed** [comment]
Ran vmprof without the mem and lines flag and that works..

**Comment by planrich** [comment]
On which test suite did you run vmprof on? Is the project public?

**Comment by boxed** [comment]
Proprietary I'm afraid. It's rather big too so that might be a factor maybe? I'll continue investigating tomorrow if I get some time over.
