### ISSUE TITLE
Connection refused message.

### ISSUE THREAD

**Issue by CrazyCasta** [vmprof/vmprof-python#170]
Not sure what's going on here. I'm running the latest (0.4.11) vmprof. File size is fairly small.

```
$ python -m vmprof.upload output.log 
Uploading to http://vmprof.com...
 => Uploading the cpu profile...
server rejected meta data. status: 400, msg: '["could not extract meta data for ff6cc61f-e4a0-4e6a-9230-bd63c834b212. exception: [Errno 111] Connection refused"]'
Traceback (most recent call last):
  File "/usr/lib64/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/crazycasta/code/GPS4/ve_cpython35/lib/python3.5/site-packages/vmprof/upload.py", line 22, in <module>
    main()
  File "/home/crazycasta/code/GPS4/ve_cpython35/lib/python3.5/site-packages/vmprof/upload.py", line 19, in main
    'VM': interpname })
  File "/home/crazycasta/code/GPS4/ve_cpython35/lib/python3.5/site-packages/vmshare/service.py", line 123, in post
    Service.FILE_CPU_PROFILE, compress=False)
  File "/home/crazycasta/code/GPS4/ve_cpython35/lib/python3.5/site-packages/vmshare/service.py", line 105, in post_file
    self.stop_if_error_occured(response)
  File "/home/crazycasta/code/GPS4/ve_cpython35/lib/python3.5/site-packages/vmshare/service.py", line 73, in stop_if_error_occured
    raise ServiceException()
vmshare.service.ServiceException
$ ls -l output.log 
-rw-r--r-- 1 crazycasta crazycasta 71202 Feb 26 17:18 output.log

```

**Comment by CrazyCasta** [comment]
[output.log](https://github.com/vmprof/vmprof-python/files/1760752/output.log)

**Comment by CrazyCasta** [comment]
P.S. I ran my own server from https://github.com/vmprof/vmprof-server and it worked fine. Is there a server issue?

**Comment by planrich** [comment]
Hi, thanks for pointing this out. Indeed part of the service did not run. Should work now. Can you verify?

**Comment by CrazyCasta** [comment]
Yep, all working now.

**Comment by kolypto** [comment]
Same issue with my first profile upload
