### ISSUE TITLE
vmprof.com is not working properly

### ISSUE THREAD

**Issue by antocuni** [vmprof/vmprof-python#182]
Just tried to upload a sample profile:
```
$ python -m vmprof --web richards.py 
/home/antocuni/.local/lib/python2.7/site-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Richards benchmark (Python) starting... [<function entry_point at 0x7f4802412aa0>]
finished.
Total time for 10 iterations: 1.43 secs
Average time per iteration: 142.82 ms
Uploading to http://vmprof.com...
 => Uploading the cpu profile...
server rejected meta data. status: 400, msg: '["could not extract meta data for 6e19e2ac-ce9f-4a2a-8927-7e04f9edd75f. exception: [Errno 111] Connection refused"]'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/antocuni/.local/lib/python2.7/site-packages/vmprof/__main__.py", line 75, in <module>
    main()
  File "/home/antocuni/.local/lib/python2.7/site-packages/vmprof/__main__.py", line 71, in main
    show_stats(prof_name, output_mode, args)
  File "/home/antocuni/.local/lib/python2.7/site-packages/vmprof/__main__.py", line 28, in show_stats
    'VM': platform.python_implementation() })
  File "/home/antocuni/.local/lib/python2.7/site-packages/vmshare/service.py", line 123, in post
    Service.FILE_CPU_PROFILE, compress=False)
  File "/home/antocuni/.local/lib/python2.7/site-packages/vmshare/service.py", line 105, in post_file
    self.stop_if_error_occured(response)
  File "/home/antocuni/.local/lib/python2.7/site-packages/vmshare/service.py", line 73, in stop_if_error_occured
    raise ServiceException()
ServiceException
```

The profile **has** been created on vmprof.com, but it's not really showing anything:
http://vmprof.com/#/6e19e2ac-ce9f-4a2a-8927-7e04f9edd75f

**Comment by boxed** [comment]
I just go this too. This has been lying here for a long time.

**Comment by boxed** [comment]
I installed vmprof-server and it works fine to upload to a local instance.
