### ISSUE TITLE
breaks on a simple script

### ISSUE THREAD

**Issue by dimaqq** [vmprof/vmprof-python#19]
Sorry my script `application.py` is propriatory.
If the error is not obvious, please let me know and I can strip that down or obfuscate it

```py
(plc)[dima@bmg 18src]$ python -m vmprof --web http://localhost:8000/ application.py
Compiling and uploading to http://localhost:8000/...
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/dima/plc/lib/python2.7/site-packages/vmprof-0.0.9-py2.7-linux-x86_64.egg/vmprof/__main__.py", line 105, in <module>
    main()
  File "/dima/plc/lib/python2.7/site-packages/vmprof-0.0.9-py2.7-linux-x86_64.egg/vmprof/__main__.py", line 102, in main
    show_stats(prof_file.name, output_mode, args)
  File "/dima/plc/lib/python2.7/site-packages/vmprof-0.0.9-py2.7-linux-x86_64.egg/vmprof/__main__.py", line 74, in show_stats
    vmprof.com.send(stats, args)
  File "/dima/plc/lib/python2.7/site-packages/vmprof-0.0.9-py2.7-linux-x86_64.egg/vmprof/com.py", line 13, in send
    "profiles": t.get_tree().flatten()._serialize(),
  File "/dima/plc/lib/python2.7/site-packages/vmprof-0.0.9-py2.7-linux-x86_64.egg/vmprof/stats.py", line 67, in get_tree
    top_addr = self.profiles[0][0][0]
IndexError: list index out of range
```

**Comment by xando** [comment]
In very odd way this says "no profiles here". 
The same as https://github.com/vmprof/vmprof-python/issues/18
