### ISSUE TITLE
Support arm64

### ISSUE THREAD

**Issue by oberstet** [vmprof/vmprof-python#192]
It would be great if vmprof supported arm64! =)

Background: we would like to ship vmprof natively integrated with crossbar to allow tracking down and monitoring performance and profiles in production. Eg pls see the benchmark reports [here](https://crossbario.com/docs/crossbarfx/scaling/benchmarks.html) which contain vmprof profiles (flamegraphs from those).

However, it seems, vmprof currently does not support arm64 (neither on cpy nor on an not yet existing pypy):

```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xawf3qqx/vmprof/setup.py", line 65, in <module>
        raise NotImplementedError("platform {} is not supported".format(platform.machine()))
    NotImplementedError: platform aarch64 is not supported
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-xawf3qqx/vmprof/
You are using pip version 18.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

here is info about the build machine: a qemu/aarch64 based docker container running on a x86-64 host

```
root@6b1f05cfc1be:/# apt show libunwind-dev
Package: libunwind-dev
Version: 1.1-4.1
Priority: optional
Section: libdevel
Source: libunwind
Maintainer: Daigo Moriwaki <daigo@debian.org>
Installed-Size: 2536 kB
Depends: libunwind8 (= 1.1-4.1)
Conflicts: libunwind1-dev, libunwind7-dev
Replaces: libunwind8-dev (<< 1.1-3.2)
Homepage: http://www.nongnu.org/libunwind
Tag: devel::library, role::devel-lib
Download-Size: 340 kB
APT-Manual-Installed: yes
APT-Sources: http://deb.debian.org/debian stretch/main arm64 Packages
Description: library to determine the call-chain of a program - development

root@6b1f05cfc1be:/# uname -a
Linux 6b1f05cfc1be 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 aarch64 GNU/Linux
root@6b1f05cfc1be:/# lscpu 
Architecture:          aarch64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 94
Model name:            Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz
Stepping:              3
CPU MHz:               1217.247
CPU max MHz:           3500.0000
CPU min MHz:           800.0000
BogoMIPS:              5184.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              6144K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp flush_l1d
root@6b1f05cfc1be:/# file /usr/bin/qemu-aarch64-static
bash: file: command not found
root@6b1f05cfc1be:/# ls -la /usr/bin/qemu-aarch64-static
-rwxr-xr-x 1 root root 3617104 Mar 24 10:51 /usr/bin/qemu-aarch64-static
```

**Comment by om26er** [comment]
Now that Apple is switching to aarch64, I'd say now is the right time to support the aarch64 as well.

**Comment by oberstet** [comment]
fwiw, we've just rediscovered this when trying to track down some issue with crossbar/arm64 .. too bad vmprof isn't available:(

```
Collecting vmprof
  Downloading vmprof-0.4.15.tar.gz (289 kB)
     |████████████████████████████████| 289 kB 5.5 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-083sxpps/vmprof/setup.py'"'"'; __file__='"'"'/tmp/pip-install-083sxpps/vmprof/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-083sxpps/vmprof/pip-egg-info
         cwd: /tmp/pip-install-083sxpps/vmprof/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-083sxpps/vmprof/setup.py", line 65, in <module>
        raise NotImplementedError("unknown platform.machine(): %s" %
    NotImplementedError: unknown platform.machine(): aarch64
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Failed to run 'override-build': Exit code was 1.
```

**Comment by fijal** [comment]
Hi Tobias

It's probably not that hard to add arm64 to vmprof, although we have been
pretty bad at supporting vmprof :/

Would you like to have a quick chat about the situation?

Best,
Maciej

**Comment by oberstet** [comment]
> Would you like to have a quick chat about the situation?

sure, great! I'm on pypy/irc ..

**Comment by rtalexk** [comment]
Do you have some updates here? I just faced this issue and after fixing dozends of issues in a project, this is the last one. 😪

**Comment by fijal** [comment]
Hi, vmprof on pypy should work on arm64. I'm not 100% sure it's released, but at least the trunk does work
