### ISSUE TITLE
_vmprof.enable Invalid argument  on Ubuntu 18.04 on WSL

### ISSUE THREAD

**Issue by scottbecker** [vmprof/vmprof-python#214]
I get the following error using a fresh install of pypy 7.2 and vmprof 0.4.15 on ubuntu 18.04 running under windows subsystem on linux

```
(venv3.6_pypy3_7_2) scott@DESKTOP-PRTO29B:~$ python -m vmprof --web test.py
Traceback (most recent call last):
  File "/home/scott/pypy3.6-v7.2.0-linux64/lib-python/3/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/scott/pypy3.6-v7.2.0-linux64/lib-python/3/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/scott/venv3.6_pypy3_7_2/site-packages/vmprof/__main__.py", line 75, in <module>
    main()
  File "/home/scott/venv3.6_pypy3_7_2/site-packages/vmprof/__main__.py", line 53, in main
    args.lines, native=native)
  File "/home/scott/venv3.6_pypy3_7_2/site-packages/vmprof/__init__.py", line 73, in enable
    _vmprof.enable(fileno, period, memory, lines, native, real_time)
_vmprof.VMProfError: Invalid argument
```

The values for this parameters are 
fileno=3
period=0.001
memory=False
lines=False
native=True
real_time=False

**Comment by LoHiaufung** [comment]
I met the same problem, have you solved it ?

**Comment by scottbecker** [comment]
No but you could try wsl 2 - https://docs.microsoft.com/en-us/windows/wsl/wsl2-install

**Comment by LoHiaufung** [comment]
Thanks a lot, I will try it .
