### ISSUE TITLE
"No module named _vmprof" error on Mac OS X 10.9.5 + pypy 2.6

### ISSUE THREAD

**Issue by jimhorng** [vmprof/vmprof-python#24]
Hi all, 
When I run 
```
#pypy -m vmprof test.py
No module named _vmprof; 'vmprof' is a package and cannot be directly executed
```
Another case:
```
#vmprofshow 
Traceback (most recent call last):
  File "<builtin>/app_main.py", line 75, in run_toplevel
  File "/vmprofshow", line 9, in <module>
    load_entry_point('vmprof==0.1.3', 'console_scripts', 'vmprofshow')()
  File "/site-packages/pkg_resources.py", line 352, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/site-packages/pkg_resources.py", line 2307, in load_entry_point
    return ep.load()
  File "/site-packages/pkg_resources.py", line 2021, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/site-packages/vmprof/__init__.py", line 7, in <module>
    import _vmprof
ImportError: No module named _vmprof
```
My environment:
* mac os x 10.9.5
* pypy 2.6

Thanks a lot :)

**Comment by fijal** [comment]
Hi.

vmprof on OS X is a bit experimental and was introduced after 2.6, you have to wait for the next release

**Comment by androm3da** [comment]
I got the same error on linux using portable pypy.

    Python 2.7.9 (295ee98b69288471b0fcf2e0ede82ce5209eb90b, Jun 01 2015, 17:30:31)
    [PyPy 2.6.0 with GCC 4.9.2]

**Comment by fijal** [comment]
Yes and it's the same answer, wait for pypy 2.6.1 ;-)

**Comment by androm3da** [comment]
"...and was introduced after 2.6" -- sorry, I just glossed over that part when I saw "OS X".

Looking forward to 2.6.1 ;)

**Comment by lopuhin** [comment]
Hmm, same thing on 2.6.1:

```
(pypy)netdb_demo (ui2) $ python
Python 2.7.10 (f3ad1e1e1d62, Aug 28 2015, 09:36:42)
[PyPy 2.6.1 with GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> 
(pypy)netdb_demo (ui2) $ python -c "import vmprof"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/kostia/apps/netdb_demo_2/pypy/site-packages/vmprof/__init__.py", line 6, in <module>
    import _vmprof
ImportError: No module named _vmprof
```

**Comment by fijal** [comment]
Yeah seems it does not come with prebuilt, despite the fact that it builds :-( will look why on the buildbot. Reopening for now

**Comment by androm3da** [comment]
For me, the problem seems to occur under `virtualenv` and not otherwise.

**Comment by fijal** [comment]
oh well, because it was not enabled. Fixed
