### ISSUE TITLE
Segfault when profiling service

### ISSUE THREAD

**Issue by jml** [vmprof/vmprof-python#34]
Apparently I don't quite have all the debugging symbols installed that I want, but here's the stack trace:

```
Core was generated by `/home/ubuntu/.virtualenvs/flocker-dbg/bin/python -m vmprof -o flocker-control.v'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f9bd429d245 in vmprof_unw_step (cp=0x7fffc14a6770, first_run=0) at src/vmprof.c:135
135     src/vmprof.c: No such file or directory.
(gdb) bt
#0  0x00007f9bd429d245 in vmprof_unw_step (cp=0x7fffc14a6770, first_run=0) at src/vmprof.c:135
#1  0x00007f9bd429d484 in get_stack_trace (result=0x7fffc14a6bb8, max_depth=1023, ucontext=0x7fffc14a8bc0,
    thread_id=0x7fffc14a6ba8) at src/vmprof.c:213
#2  0x00007f9bd429d531 in sigprof_handler (sig_nr=27, info=0x7fffc14a8cf0, ucontext=0x7fffc14a8bc0) at src/vmprof.c:232
#3  <signal handler called>
#4  cpyprof_PyEval_EvalFrameEx (f=0x7f9bd4299db1 <cpyprof_PyEval_EvalFrameEx>, throwflag=44270928) at src/_vmprof.c:44
#5  0x00000000409e6015 in ?? ()
#6  0x00007f9bd0b67b28 in ?? ()
#7  0x00007fffc14a92f0 in ?? ()
#8  0x0000000002a386d8 in ?? ()
#9  0x0000000000524b9a in PyEval_EvalCodeEx (co=0x0, globals=0x0, locals=0x0, args=0x0, argcount=0, kws=0x0,
    kwcount=5393306, defs=0x7f9b00000000, defcount=0, closure=0x2af79a8) at ../Python/ceval.c:3252
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)
```

**Comment by fijal** [comment]
it might be a threading issue, can you try again with a new version? I'm not closing that one

**Comment by fijal** [comment]
So we did a major revamp that by now does not use libunwind. Sorry it took so long, but it was a MAJOR change, I'm going to close this
