### ISSUE TITLE
PyPy/OS X: reader.py can't parse `vmmap` output

### ISSUE THREAD

**Issue by jamadden** [vmprof/vmprof-python#36]
On OS X with a self-translated PyPy 2.6.1, `_vmprof` uses the `vmmap` executable to produce output that becomes part of the profile data. This output has header lines and lines of a different format than expected that cause `vmprof.reader:read_ranges` to fail with `ValueError` and `IndexError`. For example:
```
  File "//site-packages/vmprof/profiler.py", line 31, in read_profile
    period, profiles, virtual_symbols, libs, interp_name = read_prof(prof)
  File "//site-packages/vmprof/reader.py", line 173, in read_prof
    symmap = read_ranges(fileobj.read())
  File "//site-packages/vmprof/reader.py", line 90, in read_ranges
    start, end = parts[0].split('-')
ValueError: expected length 2, got 1
```

Example output from a profile log: (This is with XCode 6.1, but I get the same results with XCode 7)
```
Pro
cess:         pypy [10569]
Path:            //bin/pypy
Load Address:    0x107e6f000
Identifier:      pypy
Version:         ???
Code Type:       X86-64
Parent Process:  bash [41008]

Date/Time:       2015-09-22 14:49:01.181 -0500
Launch Time:     2015-09-22 14:48:39.313 -0500
OS Version:      Mac OS X 10.11 (15A282b)
Report Version:  7
Analysis Tool:   /usr/bin/vmmap
----

Virtual Memory Map of process 10569 (python)
Output report format:  2.4  -- 64-bit process
VM page size:  4096 bytes

==== Non-writable regions for process 10569
REGION TYPE                      START - END             [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
__TEXT                 0000000107e6f000-0000000107e70000 [    4K] r-x/rwx SM=COW  /Users/jmadden/Projects/VirtualEnvs/relstoragepypy/bin/pypy
__LINKEDIT             0000000107e71000-0000000107e72000 [    4K] r--/rwx SM=COW  /Users/jmadden/Projects/VirtualEnvs/relstoragepypy/bin/pypy
MALLOC metadata        0000000107e73000-0000000107e74000 [    4K] r--/rwx SM=COW
MALLOC metadata        0000000107e75000-0000000107e76000 [    4K] r--/rwx SM=COW
__TEXT                 0000000107e77000-0000000107ec0000 [  292K] r-x/rwx SM=COW  /opt/local/lib/libssl.1.0.0.dylib
__LINKEDIT             0000000107ecb000-0000000107edd000 [   72K] r--/rwx SM=COW  /opt/local/lib/libssl.1.0.0.dylib
shared memory          0000000107edd000-0000000107ede000 [    4K] r--/rw- SM=SHM
__TEXT                 0000000107ede000-0000000107edf000 [    4K] r-x/rwx SM=COW  /Users/jmadden/bin/pypy-2.6.1-osx64/lib_pypy/_pwdgrp_cffi.pypy-26.so
__LINKEDIT             0000000107ee0000-0000000107ee1000 [    4K] r--/rwx SM=COW  /Users/jmadden/bin/pypy-2.6.1-osx64/lib_pypy/_pwdgrp_cffi.pypy-26.so
__TEXT                 0000000107ee1000-0000000107eeb000 [   40K] r-x/rwx SM=COW  /opt/local/lib/libintl.8.dylib
__LINKEDIT             0000000107eec000-0000000107eef000 [   12K] r--/rwx SM=COW  /opt/local/lib/libintl.8.dylib
__TEXT                 0000000107ef0000-0000000107ef1000 [    4K] r-x/rwx SM=COW  ...ughtPlatform/nti.dataserver-buildout/sources/persistent/persistent/__pycache__/_cffi__g4bdcd39cx2c90fb3d.pypy-26.so
__LINKEDIT             0000000107ef2000-0000000107ef3000 [    4K] r--/rwx SM=COW  ...ughtPlatform/nti.dataserver-buildout/sources/persistent/persistent/__pycache__/_cffi__g4bdcd39cx2c90fb3d.pypy-26.so
__TEXT                 0000000107ef3000-00000001092ba000 [ 19.8M] r-x/rwx SM=COW  /Users/jmadden/Projects/pypy-2.6.1-src/pypy/goal/libpypy-c.dylib
__LINKEDIT             000000010a56c000-000000010b973000 [ 20.0M] r--/rwx SM=COW  /Users/jmadden/Projects/pypy-2.6.1-src/pypy/goal/libpypy-c.dylib
```

I can hack around it by adding some `except` clauses, like follows, but that's probably not the right solution. I'm guessing the parser was designed for FreeBSD's output, based on the comments in `vmprof_main.h`, but I don't have an example of that handy.
```python
		if procstat:
			start, end = parts[1], parts[2]
		else:
			try:
				start, end = parts[1].split('-')
			except (ValueError, IndexError):
				#print('skipping', parts)
				continue
		try:
			start = int(start, 16)
			end = int(end, 16)
		except ValueError:
			#print("Non int", parts)
			continue
```

The above hack lets `vmprofshow` continue running, but it eventually fails with an `EmptyProfileFile` exception. I'm not yet sure if that's related or a different issue:
```
WARNING: cannot read symbols for ...ughtPlatform/nti.dataserver-buildout/sources/persistent/persistent/__pycache__/_cffi__g4bdcd39cx2c90fb3d.pypy-26.so
WARNING: cannot read symbols for ...ojects/VirtualEnvs/relstoragepypy/site-packages/psycopg2cffi/_impl/__pycache__/_cffi__g5f6f4457x182e618d.pypy-26.so
WARNING: cannot read symbols for /usr/lib/system/libunc.dylib
WARNING: cannot read symbols for /usr/lib/system/liblaunch.dylib
WARNING: cannot read symbols for __LINKEDIT
WARNING: cannot read symbols for DefaultMallocZone_0x107e73000
WARNING: cannot read symbols for 1
WARNING: cannot read symbols for 0
//site-packages/vmprof/addrspace.py:168: UserWarning: there are only 0 profiles, data will be unreliable
  warnings.warn("there are only %d profiles, data will be unreliable" % (len(filtered_profiles),))
//site-packages/vmprof/addrspace.py:170: UserWarning: there are 4629 broken profiles out of 0, data will be unreliable
  warnings.warn("there are %d broken profiles out of %d, data will be unreliable" % (skipped, len(filtered_profiles)))
Traceback (most recent call last):
  File "//bin/vmprofshow", line 9, in <module>
    load_entry_point('vmprof==0.1.5.1', 'console_scripts', 'vmprofshow')()
  File "//site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "//site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "//site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "//site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "//site-packages/vmprof/show.py", line 115, in main
    pp.show(profile)
  File "//site-packages/vmprof/show.py", line 50, in show
    tree = stats.get_tree()
  File "//site-packages/vmprof/stats.py", line 75, in get_tree
    raise EmptyProfileFile()
EmptyProfileFile
```

**Comment by jamadden** [comment]
The `EmptyProfileFile` seems to be because all traces that are read from the file are only of depth 1, so they are excluded. So unrelated to parsing the address maps.

**Comment by fijal** [comment]
This one is fixed, however I'm still fighting with OS X support, expect a new release containing it
