### ISSUE TITLE
Error when parsing vmprof ouput on OS X 10.11

### ISSUE THREAD

**Issue by lopuhin** [vmprof/vmprof-python#38]
pypy -m vmprof program.py fails:

```
$ python
Python 2.7.10 (65ac40781e5e, Oct 21 2015, 07:05:18)
[PyPy 4.0.0 with GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
$ pip freeze | grep vmprof
vmprof==0.1.5.3
$ python -m vmprof ~/programming/bench/fib.py
Traceback (most recent call last):
  File "/Users/kostia/opt/pypy-c-jit-80368-65ac40781e5e-osx64/lib-python/2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/kostia/opt/pypy-c-jit-80368-65ac40781e5e-osx64/lib-python/2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/kostia/apps/netdb_demo_2/pypy/site-packages/vmprof/__main__.py", line 67, in <module>
    main()
  File "/Users/kostia/apps/netdb_demo_2/pypy/site-packages/vmprof/__main__.py", line 64, in main
    show_stats(prof_file.name, output_mode, args)
  File "/Users/kostia/apps/netdb_demo_2/pypy/site-packages/vmprof/__main__.py", line 19, in show_stats
    virtual_only=not args.enable_nonvirtual
  File "/Users/kostia/apps/netdb_demo_2/pypy/site-packages/vmprof/profiler.py", line 31, in read_profile
    period, profiles, virtual_symbols, libs, interp_name = read_prof(prof)
  File "/Users/kostia/apps/netdb_demo_2/pypy/site-packages/vmprof/reader.py", line 173, in read_prof
    symmap = read_ranges(fileobj.read())
  File "/Users/kostia/apps/netdb_demo_2/pypy/site-packages/vmprof/reader.py", line 90, in read_ranges
    start, end = parts[0].split('-')
ValueError: expected length 2, got 1
```

If I ignore the error and print ``parts`` (with additional !!), I get the following https://gist.github.com/lopuhin/45fb12202cf73e130d58

**Comment by fijal** [comment]
Vmprof does not work on OS X. I fixed the above issues, but there are still some remaining. There is a major refactoring on the way

**Comment by fijal** [comment]
That one is fixed with the refactoring, closing
