### ISSUE TITLE
Python3 uploading issue with bytes/str

### ISSUE THREAD

**Issue by anntzer** [vmprof/vmprof-python#39]
```
$ echo 'for _ in range(int(1e8)): pass' > foo.py && python3 -mvmprof --web foo.py
<elided WARNINGS regarding unreadable symbols>
/home/antony/.local/lib/python3.5/site-packages/vmprof/addrspace.py:170: UserWarning: there are 136 broken profiles out of 1091, data will be unreliable
  warnings.warn("there are %d broken profiles out of %d, data will be unreliable" % (skipped, len(filtered_profiles)))
Compiling and uploading to http://vmprof.com...
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/antony/.local/lib/python3.5/site-packages/vmprof/__main__.py", line 67, in <module>
    main()
  File "/home/antony/.local/lib/python3.5/site-packages/vmprof/__main__.py", line 64, in main
    show_stats(prof_file.name, output_mode, args)
  File "/home/antony/.local/lib/python3.5/site-packages/vmprof/__main__.py", line 25, in show_stats
    upload_stats(stats, args)
  File "/home/antony/.local/lib/python3.5/site-packages/vmprof/__main__.py", line 36, in upload_stats
    res = vmprof.upload.upload(stats, name, argv, host, auth)
  File "/home/antony/.local/lib/python3.5/site-packages/vmprof/upload.py", line 35, in upload
    return "http://" + host + "/#/" + val[1:-1]
TypeError: Can't convert 'bytes' object to str implicitly
```

Note that the file is actually uploaded correctly.

Arch Linux standard packages (Python 3.5.0).

**Comment by fijal** [comment]
should be fixed, thanks for reporting
