### ISSUE TITLE
Vmprof crashes sometimes on Windows

### ISSUE THREAD

**Issue by ARostovsky** [vmprof/vmprof-python#51]
Actually it happens very frequently (once in around 3 runs)
OS is Windows 8.1, Python version is 2.7, vmprof version is 0.2.3.1.

```
Faulting application name: python.exe, version: 0.0.0.0, time stamp: 0x5560ad83
Faulting module name: MSVCR90.dll, version: 9.0.30729.8387, time stamp: 0x51ea24a5
Exception code: 0xc0000417
Fault offset: 0x00069f9b
Faulting process ID: 0x1b78
Faulting application start time: 0x01d1545ba0da47c4
Faulting application path: C:\Python\Python27\python.exe
Faulting module path: C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.8387_none_5094ca96bcb6b2bb\MSVCR90.dll
Report ID: de95ccc2-c04e-11e5-8299-448a5ba34f1a
Faulting package full name: 
Faulting package-relative application ID: 
```

Please take a look at my capture, which is hosted here: http://www.fastswf.com/P8_n-do

**Comment by fijal** [comment]
I'll have a look. Any chance I can get hold of your program?

**Comment by ARostovsky** [comment]
Yeap, here it is.
```
"""Project Euler problem 7 solve"""
from __future__ import print_function
import math
import sys


def is_prime(num):
    """Checks if num is prime number"""
    for i in range(2, int(math.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True


def get_prime_numbers(count):
    """Get 'count' prime numbers"""
    prime_numbers = [2]
    next_number = 3

    while len(prime_numbers) < count:
        if is_prime(next_number):
            prime_numbers.append(next_number)
        next_number += 1

    return prime_numbers


if __name__ == '__main__':
    try:
        count = int(sys.argv[1])
    except (TypeError, ValueError, IndexError):
        sys.exit("Usage: euler_7.py number")
    if count < 1:
        sys.exit("Error: number must be greater than zero")

    prime_numbers = get_prime_numbers(count)
    print("Answer: %d" % prime_numbers[-1])
```

**Comment by fijal** [comment]
So my windows 8.1 (from modern.ie) cannot reproduce it. Can you show me the traceback (or where it crashes) from visual studio or something? (I run the same thing with multiple numbers)

**Comment by ARostovsky** [comment]
Unfortunately I don't have visual studio, but i've sent several generated crash dumps to you via email.

**Comment by fijal** [comment]
ok, it'll take a while. Did you build vmprof with debugging symbols? if not, please do

**Comment by fijal** [comment]
ok, the dumps are very minimal, I'll see what I can do

**Comment by mattip** [comment]
I also could not reproduce on windows 8.1, using visual studio 9 compiler. Python startup prints out

   Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on win32

**Comment by ARostovsky** [comment]
I got this error today, is it connected with each other?
```
Traceback (most recent call last):
  File "C:\Python\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python\Python27\lib\site-packages\vmprof\__main__.py", line 69, in <module>
    main()
  File "C:\Python\Python27\lib\site-packages\vmprof\__main__.py", line 64, in main
    show_stats(prof_name, output_mode, args)
  File "C:\Python\Python27\lib\site-packages\vmprof\__main__.py", line 17, in show_stats
    stats = vmprof.read_profile(filename)
  File "C:\Python\Python27\lib\site-packages\vmprof\profiler.py", line 32, in read_profile
    period, profiles, virtual_symbols, interp_name = read_prof(prof)
  File "C:\Python\Python27\lib\site-packages\vmprof\reader.py", line 98, in read_prof
    profiles.append((trace, 1, thread_id))
MemoryError
```

My python is Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32.

**Comment by fijal** [comment]
well, that essentially means that your profile is a bit too big to handle
(using pypy would actually probably work, since pypy is more memory
efficient).

I'm working on a tool that would process those bit by bit, so we would not
run into those issues (storing 100s of megabytes log files isn't cool
either)

**Comment by fijal** [comment]
That boils down it seems to a race condition. Fixed for now, try again
