### ISSUE TITLE
Vmprof doesn't run on linux with latest PyPy

### ISSUE THREAD

**Issue by ARostovsky** [vmprof/vmprof-python#52]
I tried to measure one of my scripts using latest PyPy (4.1.0-alpha0) on Linux, but unfortunately I got such error:
'''
Traceback (most recent call last):
  File "/home/hatari/pypy/lib-python/2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/hatari/pypy/lib-python/2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/hatari/pypy/site-packages/vmprof/__main__.py", line 69, in <module>
    main()
  File "/home/hatari/pypy/site-packages/vmprof/__main__.py", line 54, in main
    vmprof.enable(prof_file.fileno(), args.period)
  File "/home/hatari/pypy/site-packages/vmprof/__init__.py", line 43, in enable
    _vmprof.enable(fileno, period)
VMProfError: libunwind.so: cannot open shared object file: No such file or directory
'''
Could you please advise me something here? Or it's a bug?
Vmprof version is 0.2.3.2.

**Comment by fijal** [comment]
hi

vmprof requires vmprof-newstack branch (I thought I merged it, but I actually didn't). We introduced thread locals to fix the thread issues, but they broke stuff, I'm busy debugging right now.

**Comment by fijal** [comment]
I'm closing this one, this is fixed.
