### ISSUE TITLE
vmprofshow cannot handle PyPy profile output

### ISSUE THREAD

**Issue by sabauma** [vmprof/vmprof-python#53]
`vmprofshow` is able to read and display the profiles generated by CPython, but crashes when populating the output for a profile generated by PyPy.  Below is the traceback for the profile of `cpuburn` benchmark run under PyPy.

```
12:24:33 $ vmprofshow vmprof_cpuburn.dat
100.0%  <module>  100.0%  tests/cpuburn.py:1
Traceback (most recent call last):
  File "/home/spenser/pypy-env/bin/vmprofshow", line 9, in <module>
    load_entry_point('vmprof==0.2.3.2', 'console_scripts', 'vmprofshow')()
  File "/home/spenser/pypy-env/site-packages/click-6.2-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/spenser/pypy-env/site-packages/click-6.2-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/spenser/pypy-env/site-packages/click-6.2-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/spenser/pypy-env/site-packages/click-6.2-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/spenser/pypy-env/site-packages/vmprof-0.2.3.2-py2.7.egg/vmprof/show.py", line 113, in main
    pp.show(profile)
  File "/home/spenser/pypy-env/site-packages/vmprof-0.2.3.2-py2.7.egg/vmprof/show.py", line 50, in show
    self._print_tree(tree)
  File "/home/spenser/pypy-env/site-packages/vmprof-0.2.3.2-py2.7.egg/vmprof/show.py", line 102, in _print_tree
    self._walk_tree(None, tree, 0, print_node)
  File "/home/spenser/pypy-env/site-packages/vmprof-0.2.3.2-py2.7.egg/vmprof/show.py", line 58, in _walk_tree
    self._walk_tree(node, c, level, callback)
  File "/home/spenser/pypy-env/site-packages/vmprof-0.2.3.2-py2.7.egg/vmprof/show.py", line 53, in _walk_tree
    callback(parent, node, level)
  File "/home/spenser/pypy-env/site-packages/vmprof-0.2.3.2-py2.7.egg/vmprof/show.py", line 95, in print_node
    raise Exception("fail!")
Exception: fail!
```

System info:

```
$ pypy --version
Python 2.7.10 (4.0.1+dfsg-1~ppa1~ubuntu15.04, Nov 20 2015, 19:34:27)
[PyPy 4.0.1 with GCC 4.9.2]

$ uname -a
Linux Mentat 4.2.0-25-generic #30-Ubuntu SMP Mon Jan 18 12:31:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by fijal** [comment]
Yes, we need to update the pypy from vmprof-newstack branch. I'm on holiday right now, otherwise working on it

**Comment by planrich** [comment]
This issue should be fixed as soon as 0.4.0 is released. The goal is that PyPy and CPython share the same code base to generate the profile.

**Comment by planrich** [comment]
Though I have to mention that it might not work for profiles that have already been generated.

**Comment by planrich** [comment]
I'm closing this now. It should work and has been released
