### ISSUE TITLE
vmprof.show always raises vmprof.stats.EmptyProfileFile exception 

### ISSUE THREAD

**Issue by traff** [vmprof/vmprof-python#73]
For any profile the following exception is raised:

``
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vmprof-0.1.5.5-py2.7-macosx-10.6-intel.egg/vmprof/show.py", line 117, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vmprof-0.1.5.5-py2.7-macosx-10.6-intel.egg/vmprof/show.py", line 113, in main
    pp.show(profile)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vmprof-0.1.5.5-py2.7-macosx-10.6-intel.egg/vmprof/show.py", line 48, in show
    tree = stats.get_tree()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vmprof-0.1.5.5-py2.7-macosx-10.6-intel.egg/vmprof/stats.py", line 100, in get_tree
    top = self.get_top(self.profiles)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vmprof-0.1.5.5-py2.7-macosx-10.6-intel.egg/vmprof/stats.py", line 74, in get_top
    raise EmptyProfileFile()
vmprof.stats.EmptyProfileFile
``

**Comment by traff** [comment]
Works with the latest version.
