### ISSUE TITLE
vmprof generates malfunction output with 64 bit Python in Windows

### ISSUE THREAD

**Issue by Kojoley** [vmprof/vmprof-python#85]
Synopsis:

```
>python -m vmprof -o prof-x64.log sometest.py

>python -m vmprof.upload prof-x64.log
Traceback (most recent call last):
  File "C:\Python27_x64\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27_x64\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27_x64\lib\site-packages\vmprof\upload.py", line 105, in <module>
    main()
  File "C:\Python27_x64\lib\site-packages\vmprof\upload.py", line 94, in main
    stats = vmprof.read_profile(args.profile)
  File "C:\Python27_x64\lib\site-packages\vmprof\profiler.py", line 34, in read_profile
    period, profiles, virtual_symbols, interp_name = read_prof(prof_file)
  File "C:\Python27_x64\lib\site-packages\vmprof\reader.py", line 172, in read_prof
    assert read_word(fileobj) == 0 # header count
  File "C:\Python27_x64\lib\site-packages\vmprof\binary.py", line 19, in read_word
    r = int(struct.unpack('l', b)[0])
struct.error: unpack requires a string argument of length 4

>python -V
Python 2.7.12

>python -c "import sys; print(sys.version)"
2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
```

It works with x86 Python:

```
>python -m vmprof -o prof-x86.log sometest.py

>python -m vmprof.upload prof-x86.log
Compiling and uploading to http://vmprof.com...
VMProf log: http://vmprof.com/#/e6881666e8da424f33b18ecfd767d708

C:\Working\Repositories>python -V
Python 2.7.12

C:\Working\Repositories>python -c "import sys; print(sys.version)"
2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
```

```
>python -m vmprof.upload prof-x64.log
Traceback (most recent call last):
  File "C:\Python27_x86\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27_x86\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27_x86\lib\site-packages\vmprof\upload.py", line 105, in <module>
    main()
  File "C:\Python27_x86\lib\site-packages\vmprof\upload.py", line 94, in main
    stats = vmprof.read_profile(args.profile)
  File "C:\Python27_x86\lib\site-packages\vmprof\profiler.py", line 34, in read_profile
    period, profiles, virtual_symbols, interp_name = read_prof(prof_file)
  File "C:\Python27_x86\lib\site-packages\vmprof\reader.py", line 231, in read_prof
    assert not marker, (fileobj.tell(), repr(marker))
AssertionError: (69L, "'0'")
```

The content of `sometest.py`:

``` python
import time

for _ in xrange(1000):
    time.sleep(.001)
```

Feel free to ask for additional information which can help to resolve this issue. Thanks!

**Comment by Kojoley** [comment]
I have updated issue after figuring out that the cause is 64 bit Python.

Running tests from `tests` folder gives nothing new :(
```
>python tests/cpuburn.py
Running for 30 seconds ..

Actual run-time: 1058.00008774 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1050.99987984 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1053.00021172 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1055.00006676 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1049.99995232 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1049.0000248 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1051.00011826 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1047.00016975 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1048.99978638 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1050.99987984 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1049.99995232 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1048.00009727 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1049.99995232 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1049.99995232 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1049.99995232 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1052.00004578 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1052.00004578 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1055.00006676 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1049.0000248 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1052.9999733 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1044.99983788 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1044.00014877 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1049.99995232 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1047.99985886 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1046.99993134 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1051.00011826 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1063.99989128 / Requested run-time: 1000, 13 iterations. Total iterations: 1300000
Actual run-time: 1003.9999485 / Requested run-time: 1000, 13 iterations. Total iterations: 1300000
Actual run-time: 1064.0001297 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1049.0000248 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000

Profile written to vmprof_cpuburn.dat.
To view the profile, run: vmprofshow vmprof_cpuburn.dat

>vmprofshow vmprof_cpuburn.dat
Fatal: could not read vmprof profile file 'vmprof_cpuburn.dat': unpack requires a string argument of length 4

>python tests/test_reader.py

>python tests/test_config.py

>python tests/test_run.py

>python tests/test_stats.py
```

**Comment by planrich** [comment]
Hi, thanks for digging. I'll have a look just now.

**Comment by Kojoley** [comment]
Perhaps this will be useful:
```
Linux-3.16.0-4-amd64-x86_64-with-debian-8.5
2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2]
struct.calcsize('Q') == 8
struct.calcsize('L') == 8

Windows-7-6.1.7601-SP2
2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
struct.calcsize('Q') == 8
struct.calcsize('L') == 4

Windows-7-6.1.7601-SP2
2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
struct.calcsize('Q') == 8
struct.calcsize('L') == 4
```

**Comment by rserbitar** [comment]
Any news on the subject? This is really preventing us from using this profiler.

**Comment by planrich** [comment]
yes, I have found 2 issues recently. I did not yet push them there is still something wrong with the profile generation (sadly). I'll comment here when I make more progress!

**Comment by divenex** [comment]
PyCharrm 2016.3 just introduced line profiling with vmprof https://www.jetbrains.com/pycharm/whatsnew/#v2016-3-line-profiling

I have just realized that this very nice new feature does not actually work on Windows 64bit (the most popular among developers), due to vmprof not yet supporting Windows 64bit...

A vmprof fix would affect many people!

**Comment by rserbitar** [comment]
Any news?

**Comment by planrich** [comment]
Not yet, but this will be fixed soon. I plan to release this with the native profiling or shortly after. Sorry for the inconvenience

**Comment by planrich** [comment]
I have commited a fix that passes the test suite on my windows 64 virtual machine. Will be released in 0.4.0 (or pull directly from the source tree now).

**Comment by Kojoley** [comment]
Unfortunately it does not work for me. :cry: 

commit 4da828e401a0d0d88228cae714ad2db1782cca14
<details>
  <summary>python vmprof/test/cpuburn.py && vmprofshow vmprof_cpuburn.dat</summary>
  <p>

```
>python vmprof/test/cpuburn.py
Running for 30 seconds ..

Actual run-time: 1016.9999599456787 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1021.0001468658447 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1019.9999809265137 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1017.9998874664307 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1021.0001468658447 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1010.9999179840088 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1019.9999809265137 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1013.9999389648438 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1027.0001888275146 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1006.9999694824219 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1015.0001049041748 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1018.9998149871826 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1019.0000534057617 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1026.0000228881836 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1012.0000839233398 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1022.9997634887695 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1012.0000839233398 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1022.0000743865967 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1008.9998245239258 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1015.0001049041748 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1016.0000324249268 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1032.0000648498535 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1013.9999389648438 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1017.9998874664307 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1015.9997940063477 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1026.0000228881836 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1026.0000228881836 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1026.0000228881836 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1000.999927520752 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1008.0001354217529 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000

Profile written to vmprof_cpuburn.dat.
To view the profile, run: vmprofshow vmprof_cpuburn.dat

>vmprofshow vmprof_cpuburn.dat
Fatal: could not read vmprof profile file 'vmprof_cpuburn.dat': (311671311, "b'p'")
```

  </p>
</details>

<details>
  <summary>py.test vmprof/ -vra</summary>
  <p>

```
>py.test vmprof/ -vra
============================= test session starts =============================
platform win32 -- Python 3.5.3, pytest-3.0.6, py-1.4.32, pluggy-0.4.0 -- C:\Miniconda2\envs\test-mpl-py3\python.exe
cachedir: .cache
rootdir: C:\Working\Repositories\vmprof-python, inifile: pytest.ini
plugins: xdist-1.15.0, timeout-1.2.0, mpl-0.5, cov-2.3.1, hypothesis-3.6.1
collected 27 items

vmprof/test/test_c_source.py::TestStack::test_binary_search_ranges SKIPPED
vmprof/test/test_c_source.py::TestStack::test_ignore_ip SKIPPED
vmprof/test/test_c_source.py::TestStack::test_read_vmaps SKIPPED
vmprof/test/test_c_source.py::TestStack::test_self_vmaps SKIPPED
vmprof/test/test_c_source.py::TestStack::test_read_vmaps_darwin SKIPPED
vmprof/test/test_c_source.py::TestStack::test_overflow_vmaps SKIPPED
vmprof/test/test_c_symboltable.py::TestSymbolTable::test_dump_all_known_symbols SKIPPED
vmprof/test/test_c_symboltable.py::TestSymbolTable::test_resolve_addr SKIPPED
vmprof/test/test_config.py::test_parser_config PASSED
vmprof/test/test_config.py::test_parser_arg_precedence PASSED
vmprof/test/test_config.py::test_parser_without_section PASSED
vmprof/test/test_native.py::TestNative::test_simple_sample SKIPPED
vmprof/test/test_reader.py::test_fileobj PASSED
vmprof/test/test_reader.py::test_fileobj_wrapper PASSED
vmprof/test/test_run.py::test_basic FAILED
vmprof/test/test_run.py::test_read_bit_by_bit FAILED
vmprof/test/test_run.py::test_enable_disable FAILED
vmprof/test/test_run.py::test_start_end_time FAILED
vmprof/test/test_run.py::test_nested_call FAILED
vmprof/test/test_run.py::test_multithreaded FAILED
vmprof/test/test_run.py::test_memory_measurment SKIPPED
vmprof/test/test_run.py::test_line_profiling FAILED
vmprof/test/test_run.py::test_vmprof_show FAILED
vmprof/test/test_run.py::TestNative::test_gzip_call SKIPPED
vmprof/test/test_stats.py::test_tree_basic PASSED
vmprof/test/test_stats.py::test_tree_jit PASSED
vmprof/test/test_stats.py::test_read_simple SKIPPED
=========================== short test summary info ===========================
FAIL vmprof/test/test_run.py::test_basic
FAIL vmprof/test/test_run.py::test_read_bit_by_bit
FAIL vmprof/test/test_run.py::test_enable_disable
FAIL vmprof/test/test_run.py::test_start_end_time
FAIL vmprof/test/test_run.py::test_nested_call
FAIL vmprof/test/test_run.py::test_multithreaded
FAIL vmprof/test/test_run.py::test_line_profiling
FAIL vmprof/test/test_run.py::test_vmprof_show
SKIP [1] vmprof\test\test_c_symboltable.py:59: condition: sys.platform == 'win32'
SKIP [1] vmprof\test\test_stats.py:35: think later
SKIP [1] vmprof\test\test_c_source.py:55: condition: sys.platform == 'win32'
SKIP [1] vmprof\test\test_run.py:205: unsupported platform
SKIP [1] vmprof\test\test_run.py:374: condition: sys.platform == 'win32'
SKIP [1] vmprof\test\test_native.py:29: condition: sys.platform == 'win32'
SKIP [1] vmprof\test\test_c_source.py:109: condition: not sys.platform.startswith('darwin')
SKIP [1] vmprof\test\test_c_source.py:92: condition: not sys.platform.startswith('linux')
SKIP [1] vmprof\test\test_c_source.py:37: condition: sys.platform == 'win32'
SKIP [1] vmprof\test\test_c_source.py:113: condition: not sys.platform.startswith('linux')
SKIP [1] vmprof\test\test_c_source.py:71: condition: not sys.platform.startswith('linux')
SKIP [1] vmprof\test\test_c_symboltable.py:102: condition: sys.platform == 'win32'

================================== FAILURES ===================================
_________________________________ test_basic __________________________________

    def test_basic():
        tmpfile = tempfile.NamedTemporaryFile(delete=False)
>       vmprof.enable(tmpfile.fileno())

vmprof\test\test_run.py:85:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

fileno = 12, period = 0.00099, memory = False, lines = False, native = False

    def enable(fileno, period=DEFAULT_PERIOD, memory=False, lines=False, native=None):
        if not isinstance(period, float):
            raise ValueError("You need to pass a float as an argument")
        gz_fileno = _gzip_start(fileno)
        native = _is_native_enabled(native)
>       _vmprof.enable(gz_fileno, period, memory, lines, native)
E       TypeError: function takes at most 4 arguments (5 given)

vmprof\__init__.py:69: TypeError
____________________________ test_read_bit_by_bit _____________________________

    def test_read_bit_by_bit():
        tmpfile = tempfile.NamedTemporaryFile(delete=False)
>       vmprof.enable(tmpfile.fileno())

vmprof\test\test_run.py:98:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

fileno = 13, period = 0.00099, memory = False, lines = False, native = False

    def enable(fileno, period=DEFAULT_PERIOD, memory=False, lines=False, native=None):
        if not isinstance(period, float):
            raise ValueError("You need to pass a float as an argument")
        gz_fileno = _gzip_start(fileno)
        native = _is_native_enabled(native)
>       _vmprof.enable(gz_fileno, period, memory, lines, native)
E       TypeError: function takes at most 4 arguments (5 given)

vmprof\__init__.py:69: TypeError
_____________________________ test_enable_disable _____________________________

    def test_enable_disable():
        prof = vmprof.Profiler()
>       with prof.measure():

vmprof\test\test_run.py:107:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
vmprof\profiler.py:24: in __enter__
    vmprof.enable(self.tmpfile.fileno(), 0.001, self.memory, native=self.native)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

fileno = 14, period = 0.001, memory = False, lines = False, native = False

    def enable(fileno, period=DEFAULT_PERIOD, memory=False, lines=False, native=None):
        if not isinstance(period, float):
            raise ValueError("You need to pass a float as an argument")
        gz_fileno = _gzip_start(fileno)
        native = _is_native_enabled(native)
>       _vmprof.enable(gz_fileno, period, memory, lines, native)
E       TypeError: function takes at most 4 arguments (5 given)

vmprof\__init__.py:69: TypeError
_____________________________ test_start_end_time _____________________________

    def test_start_end_time():
        prof = vmprof.Profiler()
        before_profile = datetime.now(pytz.utc)
>       with prof.measure():

vmprof\test\test_run.py:116:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
vmprof\profiler.py:24: in __enter__
    vmprof.enable(self.tmpfile.fileno(), 0.001, self.memory, native=self.native)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

fileno = 15, period = 0.001, memory = False, lines = False, native = False

    def enable(fileno, period=DEFAULT_PERIOD, memory=False, lines=False, native=None):
        if not isinstance(period, float):
            raise ValueError("You need to pass a float as an argument")
        gz_fileno = _gzip_start(fileno)
        native = _is_native_enabled(native)
>       _vmprof.enable(gz_fileno, period, memory, lines, native)
E       TypeError: function takes at most 4 arguments (5 given)

vmprof\__init__.py:69: TypeError
______________________________ test_nested_call _______________________________

    def test_nested_call():
        prof = vmprof.Profiler()
>       with prof.measure():

vmprof\test\test_run.py:131:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
vmprof\profiler.py:24: in __enter__
    vmprof.enable(self.tmpfile.fileno(), 0.001, self.memory, native=self.native)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

fileno = 14, period = 0.001, memory = False, lines = False, native = False

    def enable(fileno, period=DEFAULT_PERIOD, memory=False, lines=False, native=None):
        if not isinstance(period, float):
            raise ValueError("You need to pass a float as an argument")
        gz_fileno = _gzip_start(fileno)
        native = _is_native_enabled(native)
>       _vmprof.enable(gz_fileno, period, memory, lines, native)
E       TypeError: function takes at most 4 arguments (5 given)

vmprof\__init__.py:69: TypeError
_____________________________ test_multithreaded ______________________________

    def test_multithreaded():
        if '__pypy__' in sys.builtin_module_names:
            py.test.skip("not supported on pypy just yet")
        import threading
        finished = []

        def f():
            for k in range(1000):
                l = [a for a in xrange(COUNT)]
            finished.append("foo")

        threads = [threading.Thread(target=f), threading.Thread(target=f)]
        prof = vmprof.Profiler()
>       with prof.measure():

vmprof\test\test_run.py:177:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
vmprof\profiler.py:24: in __enter__
    vmprof.enable(self.tmpfile.fileno(), 0.001, self.memory, native=self.native)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

fileno = 16, period = 0.001, memory = False, lines = False, native = False

    def enable(fileno, period=DEFAULT_PERIOD, memory=False, lines=False, native=None):
        if not isinstance(period, float):
            raise ValueError("You need to pass a float as an argument")
        gz_fileno = _gzip_start(fileno)
        native = _is_native_enabled(native)
>       _vmprof.enable(gz_fileno, period, memory, lines, native)
E       TypeError: function takes at most 4 arguments (5 given)

vmprof\__init__.py:69: TypeError
_____________________________ test_line_profiling _____________________________

    def test_line_profiling():
        tmpfile = tempfile.NamedTemporaryFile(delete=False)
>       vmprof.enable(tmpfile.fileno(), lines=True, native=False)  # enable lines profiling

vmprof\test\test_run.py:308:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

fileno = 17, period = 0.00099, memory = False, lines = True, native = False

    def enable(fileno, period=DEFAULT_PERIOD, memory=False, lines=False, native=None):
        if not isinstance(period, float):
            raise ValueError("You need to pass a float as an argument")
        gz_fileno = _gzip_start(fileno)
        native = _is_native_enabled(native)
>       _vmprof.enable(gz_fileno, period, memory, lines, native)
E       TypeError: function takes at most 4 arguments (5 given)

vmprof\__init__.py:69: TypeError
______________________________ test_vmprof_show _______________________________

    def test_vmprof_show():
        tmpfile = tempfile.NamedTemporaryFile(delete=False)
>       vmprof.enable(tmpfile.fileno())

vmprof\test\test_run.py:324:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

fileno = 16, period = 0.00099, memory = False, lines = False, native = False

    def enable(fileno, period=DEFAULT_PERIOD, memory=False, lines=False, native=None):
        if not isinstance(period, float):
            raise ValueError("You need to pass a float as an argument")
        gz_fileno = _gzip_start(fileno)
        native = _is_native_enabled(native)
>       _vmprof.enable(gz_fileno, period, memory, lines, native)
E       TypeError: function takes at most 4 arguments (5 given)

vmprof\__init__.py:69: TypeError
=============== 8 failed, 7 passed, 12 skipped in 0.45 seconds ================
```

  </p>
</details>

**Comment by planrich** [comment]
Looking into that, thanks

**Comment by planrich** [comment]
Indeed there were two issues:

* Race condition if writing to log file is split into several calls (fixed)
* CPU Burn opened the file in non binary mode (some extra bytes are added while writing)

I added a FAQ entry for the latter case.

Can you try the commit 0f4bd60f?

**Comment by Kojoley** [comment]
I can confirm it works now. Thanks!
